services:
  - type: web
    name: nova-xmd-v1
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PREFIX
        value: .
      - key: PAIRING_ENABLED
        value: true
